### ISSUE TITLE
Right window SHARD_STATS snapshot ends at or before endTime

### ISSUE THREAD

**Issue by sergzin** [opendistro-for-elasticsearch/performance-analyzer#91] opened 2020-04-06 15:26 UTC
Centos 7
opendistro installed from rpm

package version `opendistro-performance-analyzer-1.2.1.0-1.noarch`

process is constantly spamming in the logs the following. 

```
Apr 06 16:59:10 lddb performance-analyzer-agent-cli[878]: 16:59:10.876 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586185143200, lw: 1586185143187, startTime: 1586185140000, endTime: 1586185145000
Apr 06 17:05:45 lddb performance-analyzer-agent-cli[878]: 17:05:45.742 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586185538147, lw: 1586185538018, startTime: 1586185535000, endTime: 1586185540000
Apr 06 17:05:50 lddb performance-analyzer-agent-cli[878]: 17:05:50.734 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586185543059, lw: 1586185543043, startTime: 1586185540000, endTime: 1586185545000
Apr 06 17:05:55 lddb performance-analyzer-agent-cli[878]: 17:05:55.784 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586185548101, lw: 1586185548060, startTime: 1586185545000, endTime: 1586185550000
Apr 06 17:06:35 lddb performance-analyzer-agent-cli[878]: 17:06:35.944 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586185588311, lw: 1586185588251, startTime: 1586185585000, endTime: 1586185590000
Apr 06 17:13:15 lddb performance-analyzer-agent-cli[878]: 17:13:15.782 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586185988183, lw: 1586185988060, startTime: 1586185985000, endTime: 1586185990000
Apr 06 17:13:20 lddb performance-analyzer-agent-cli[878]: 17:13:20.801 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586185993181, lw: 1586185993087, startTime: 1586185990000, endTime: 1586185995000
Apr 06 17:13:25 lddb performance-analyzer-agent-cli[878]: 17:13:25.854 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586185998235, lw: 1586185998110, startTime: 1586185995000, endTime: 1586186000000
Apr 06 17:13:30 lddb performance-analyzer-agent-cli[878]: 17:13:30.829 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586186003223, lw: 1586186003137, startTime: 1586186000000, endTime: 1586186005000
Apr 06 17:13:35 lddb performance-analyzer-agent-cli[878]: 17:13:35.858 [Thread-1] ERROR com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor - Right window SHARD_STATS snapshot ends at or before endTime. rw: 1586186008239, lw: 1586186008166, startTime: 1586186005000, endTime: 1586186010000
```

**Comment by yojs** [comment] 2020-08-13 23:23
Hi @sergzin ,

Thanks for reporting the issue. Have you tried the latest PA version and still facing the same issue. Please let us know some details on how to reproduce this.

thanks.

**Comment by ktkrg** [comment] 2020-08-27 23:56
Closing this due to lack of correspondence. Please feel free to reopen the issue if you are still facing this issue.

**Closed by ktkrg** 2020-08-27 23:56 UTC
Labels: bug
